name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    uses: djachenko/repokit/.github/workflows/python-release.yml@{{VERSION}}
    with:
      package_name: {{REPO}}
    secrets: inherit
    permissions:
      id-token: write
      contents: write
