name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    uses: djachenko/repokit/.github/workflows/swift-package-release.yml@{{VERSION}}
    secrets: inherit
