name: Tests

on:
  push:
    branches:
      - '**'
      - '!master'
    tags-ignore:
      - '**'

jobs:
  tests:
    uses: djachenko/repokit/.github/workflows/swift-app-tests.yml@{{VERSION}}
    secrets: inherit
