#!/bin/bash

staged_sh=$(git diff --cached --name-only --diff-filter=ACM | grep '\.sh$')

[[ -z "$staged_sh" ]] && exit 0

if command -v shfmt &> /dev/null; then
  echo "$staged_sh" | xargs shfmt -i 2 -sr -w
  echo "$staged_sh" | xargs git add
fi

if command -v shellcheck &> /dev/null; then
  if ! echo "$staged_sh" | xargs shellcheck; then
    echo "✗ shellcheck failed"
    exit 1
  fi
fi
