name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: cocogitto/cocogitto-action@v3
        with:
          git-user: repokit
          git-user-email: repokit@djachenko

      - name: Bump version
        run: cog bump --auto --disable-bump-commit

      - name: Get changelog
        run: cog changelog > /tmp/changelog.md

      - name: Push tag
        run: git push origin --tags

      - name: Create GitHub release
        id: version
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          gh release create "$VERSION" --title "$VERSION" --notes-file /tmp/changelog.md
