name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: shellcheck
        uses: shellcheck-py/shellcheck-py@v1.0.1
        with:
          scandir: '.'

      - name: shfmt
        uses: mfinelli/setup-shfmt@v3
      - run: shfmt -d .
